### ISSUE TITLE
Migrating to Astro for Performance

### ISSUE THREAD

**Issue by IsmaelPSY** [IsmaelPSY/innovando#15]
Need to migrate project to a framework because of scalability, performance and others. The option we selected was Astro.

**Comment by joseavr** [comment]
Hi Ismael! 

I would like to take this task. I have experience with Astro and I believe we can easily migrate from Vanilla JS to Astro.

Thank you.

**Comment by IsmaelPSY** [comment]
Everything OK with the migration. Thanks to @lamula21. Issue resolved with #16 PR.
